"use client";
import {useEffect,useMemo,useState} from "react";
import type {User} from "@supabase/supabase-js";
import {createClient} from "@/lib/supabase/client";

type Price={low?:number;mid?:number;market?:number};
type Card={id:string;name:string;number:string;rarity?:string;set:{id:string;name:string;releaseDate?:string};images:{small:string;large:string};tcgplayer?:{updatedAt?:string;prices?:Record<string,Price>}};
type SetItem={id:string;name:string;total:number;releaseDate:string;images:{logo:string}};
type Entry={id?:string;card_id:string;card_name:string;set_name:string;image_url:string;variant:string;variant_label:string;quantity:number;purchase_price_cents:number;market_price_cents:number;price_source?:string};
const labels:Record<string,string>={normal:"Normal",holofoil:"Holofoil",reverseHolofoil:"Reverse holofoil","1stEditionNormal":"1st Edition normal","1stEditionHolofoil":"1st Edition holofoil",unlimited:"Unlimited",unlimitedHolofoil:"Unlimited holofoil"};
const usd=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
const prices=(card:Card)=>Object.entries(card.tcgplayer?.prices||{}).map(([variant,p])=>({variant,label:labels[variant]||variant,market:Math.round((p.market||0)*100),low:Math.round((p.low||0)*100),mid:Math.round((p.mid||0)*100)})).filter(p=>p.market>0).sort((a,b)=>a.market-b.market);

export default function CardFolio(){
  const configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
  const supabase=useMemo(()=>configured?createClient():null,[configured]);
  const [view,setView]=useState<"discover"|"sets"|"portfolio">("discover"),[cards,setCards]=useState<Card[]>([]),[sets,setSets]=useState<SetItem[]>([]),[selected,setSelected]=useState<Card|null>(null),[activeSet,setActiveSet]=useState<SetItem|null>(null),[expansionCards,setExpansionCards]=useState<Card[]>([]),[portfolio,setPortfolio]=useState<Entry[]>([]),[user,setUser]=useState<User|null>(null);
  const [loading,setLoading]=useState(true),[query,setQuery]=useState(""),[priceBand,setPriceBand]=useState("all"),[sort,setSort]=useState("default"),[rarity,setRarity]=useState("all"),[page,setPage]=useState(1),[expansionPage,setExpansionPage]=useState(1),[total,setTotal]=useState(0),[expansionTotal,setExpansionTotal]=useState(0),[authOpen,setAuthOpen]=useState(false),[message,setMessage]=useState("");

  useEffect(()=>{loadCards(true);fetch("/api/sets").then(r=>r.json()).then(j=>setSets(j.data||[]));if(!supabase)return;supabase.auth.getUser().then(({data})=>setUser(data.user));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);// eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(user)loadPortfolio()},[user]);// eslint-disable-line react-hooks/exhaustive-deps
  async function loadCards(reset=false){setLoading(true);const next=reset?1:page;const terms=[];if(query)terms.push(`name:"${query}*"`);const ranges:Record<string,string>={under10:"[0.01 TO 10]",p10to50:"[10 TO 50]",p50to100:"[50 TO 100]",over100:"[100 TO *]"};if(ranges[priceBand])terms.push(`tcgplayer.prices.holofoil.market:${ranges[priceBand]}`);const order=sort==="low"?"tcgplayer.prices.holofoil.market":sort==="high"?"-tcgplayer.prices.holofoil.market":"-set.releaseDate";const params=new URLSearchParams({page:String(next),pageSize:"24",orderBy:order});if(terms.length)params.set("q",terms.join(" "));try{const r=await fetch(`/api/cards?${params}`),j=await r.json();if(!r.ok)throw Error();setCards(old=>reset?j.data:[...old,...j.data]);setTotal(j.totalCount);setPage(next+1)}catch{setMessage("Live card service is temporarily unavailable.")}finally{setLoading(false)}}
  async function openSet(set:SetItem){setActiveSet(set);setRarity("all");setExpansionPage(1);setExpansionCards([]);setView("sets");await loadSetCards(set,"all",1,true)}
  async function loadSetCards(set=activeSet,nextRarity=rarity,next=expansionPage,reset=false){if(!set)return;const terms=[`set.id:${set.id}`];if(nextRarity!=="all")terms.push(`rarity:"${nextRarity}"`);const p=new URLSearchParams({page:String(next),pageSize:"24",orderBy:"number",q:terms.join(" ")});const r=await fetch(`/api/cards?${p}`),j=await r.json();if(r.ok){setExpansionCards(old=>reset?j.data:[...old,...j.data]);setExpansionTotal(j.totalCount);setExpansionPage(next+1)}}
  async function changeRarity(value:string){setRarity(value);setExpansionCards([]);setExpansionPage(1);await loadSetCards(activeSet,value,1,true)}
  async function loadPortfolio(){if(!supabase)return;const {data}=await supabase.from("portfolio_entries").select("*").order("created_at",{ascending:false});setPortfolio(data||[]);await migrateLocal()}
  async function migrateLocal(){if(!supabase||!user)return;const legacy=localStorage.getItem("cardfolio")||localStorage.getItem("pokefolio");if(!legacy||localStorage.getItem("cardfolio-migrated"))return;try{const old=JSON.parse(legacy);for(const item of old){await supabase.from("portfolio_entries").upsert({user_id:user.id,card_id:item.id,card_name:item.name,set_name:item.set,image_url:item.image,variant:item.variant||"normal",variant_label:item.variantLabel||"Raw",quantity:item.qty||1,purchase_price_cents:Math.round((item.paid||0)*100),market_price_cents:Math.round((item.price||0)*100),price_source:item.priceSource},{onConflict:"user_id,card_id,variant,purchase_price_cents"})}localStorage.setItem("cardfolio-migrated","true")}catch{}}
  async function addCard(card:Card,variant:string,paid:number,quantity:number){if(!user){setSelected(null);setAuthOpen(true);return}if(!supabase)return;const p=prices(card).find(x=>x.variant===variant);const row={user_id:user.id,card_id:card.id,card_name:card.name,set_name:card.set.name,image_url:card.images.small,variant,variant_label:p?.label||"Raw",quantity,purchase_price_cents:Math.round(paid*100),market_price_cents:p?.market||0,price_source:p?"TCGplayer":null,price_updated_at:card.tcgplayer?.updatedAt||null};const {error}=await supabase.from("portfolio_entries").upsert(row,{onConflict:"user_id,card_id,variant,purchase_price_cents"});if(error)setMessage(error.message);else{setSelected(null);await loadPortfolio();setMessage(`${card.name} added`)}}
  async function removeEntry(id?:string){if(!supabase||!id)return;await supabase.from("portfolio_entries").delete().eq("id",id);setPortfolio(p=>p.filter(x=>x.id!==id))}
  const value=portfolio.reduce((n,e)=>n+e.market_price_cents*e.quantity,0),cost=portfolio.reduce((n,e)=>n+e.purchase_price_cents*e.quantity,0),qty=portfolio.reduce((n,e)=>n+e.quantity,0);
  return <><header className="topbar"><button className="brand plain" onClick={()=>setView("discover")}><span className="brand-mark">CF</span><span>CARDFOLIO</span></button><nav>{(["discover","sets","portfolio"] as const).map(v=><button key={v} className={`nav-link ${view===v?"active":""}`} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}{v==="portfolio"&&<span className="count">{qty}</span>}</button>)}</nav><div className="account">{user?<><small>{user.email}</small><button className="auth-btn" onClick={()=>supabase?.auth.signOut()}>Sign out</button></>:<button className="auth-btn" onClick={()=>setAuthOpen(true)}>Sign in</button>}</div></header>
  {message&&<div className="notice" role="status">{message}<button className="plain" onClick={()=>setMessage("")}> ×</button></div>}
  <main>{view==="discover"&&<section><div className="hero"><div className="eyebrow"><span/> THE COLLECTOR&apos;S EDGE</div><h1>Know the card.<br/><em>Own the market.</em></h1><p>Live raw-card market data and cloud portfolio tracking.</p><form className="search-wrap" onSubmit={e=>{e.preventDefault();loadCards(true)}}><span className="search-icon">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Pikachu, Charizard, 151…"/><button>Search cards →</button></form></div><section className="content-section"><div className="section-head"><div><span className="kicker">LIVE CATALOGUE</span><h2>Cards worth watching</h2></div><div className="price-filters"><label>PRICE<select value={priceBand} onChange={e=>{setPriceBand(e.target.value);setTimeout(()=>loadCards(true),0)}}><option value="all">All prices</option><option value="under10">Under $10</option><option value="p10to50">$10–$50</option><option value="p50to100">$50–$100</option><option value="over100">Over $100</option></select></label><label>SORT<select value={sort} onChange={e=>{setSort(e.target.value);setTimeout(()=>loadCards(true),0)}}><option value="default">Newest</option><option value="low">Price: low</option><option value="high">Price: high</option></select></label></div></div><p className="status">{total?`Showing ${cards.length} of ${total.toLocaleString()} cards · TCGplayer USD`:"Loading catalogue…"}</p><CardGrid cards={cards} loading={loading} open={setSelected}/>{cards.length<total&&<button className="load-more" onClick={()=>loadCards()}>Load more cards ↓</button>}</section></section>}
  {view==="sets"&&<section className="content-section page-view">{!activeSet?<><div className="section-head"><div><span className="kicker">THE ARCHIVE</span><h2>Explore every era</h2></div></div><div className="set-grid">{sets.map(s=><button className="set-tile" key={s.id} onClick={()=>openSet(s)}><div><span>{s.releaseDate?.slice(0,4)}</span><h3>{s.name}</h3><p>{s.total} cards</p></div><img src={s.images.logo} alt=""/></button>)}</div></>:<><div className="active-set"><img src={activeSet.images.logo} alt=""/><div><small>SET CATALOGUE</small><strong>{activeSet.name}</strong><span>{activeSet.total} cards · {activeSet.releaseDate}</span></div><button onClick={()=>setActiveSet(null)}>← All sets</button></div><div className="catalogue-tools"><label>RARITY<select value={rarity} onChange={e=>changeRarity(e.target.value)}>{["all","Illustration Rare","Special Illustration Rare","Ultra Rare","Hyper Rare","Double Rare","Rare","Uncommon","Common"].map(r=><option key={r} value={r}>{r==="all"?"All rarities":r}</option>)}</select></label></div><p className="status">Showing {expansionCards.length} of {expansionTotal} cards</p><CardGrid cards={expansionCards} loading={false} open={setSelected}/>{expansionCards.length<expansionTotal&&<button className="load-more" onClick={()=>loadSetCards()}>Load more cards ↓</button>}</>}</section>}
  {view==="portfolio"&&<section className="content-section page-view"><div className="portfolio-hero"><div><span className="kicker">YOUR COLLECTION</span><h2>Portfolio overview</h2></div></div>{!user?<div className="portfolio-login"><h3>Sign in to save your collection</h3><p>Your portfolio will sync securely across devices.</p><button className="auth-btn" onClick={()=>setAuthOpen(true)}>Sign in or create account</button></div>:<><div className="stat-grid"><article><small>MARKET VALUE</small><strong>{usd(value)}</strong></article><article><small>TOTAL INVESTED</small><strong>{usd(cost)}</strong></article><article><small>UNREALIZED RETURN</small><strong>{usd(value-cost)}</strong></article><article><small>CARDS OWNED</small><strong>{qty}</strong></article></div><div className="portfolio-list">{portfolio.map(e=><article className="portfolio-row" key={e.id}><img src={e.image_url} alt=""/><div><strong>{e.card_name}</strong><small>{e.set_name} · {e.variant_label}</small></div><div><small>QUANTITY</small><strong>{e.quantity}</strong></div><div><small>PRICE PAID</small><strong>{usd(e.purchase_price_cents)}</strong></div><div><small>MARKET VALUE</small><strong>{usd(e.market_price_cents*e.quantity)}</strong></div><div><small>RETURN</small><strong>{usd((e.market_price_cents-e.purchase_price_cents)*e.quantity)}</strong></div><button className="remove" onClick={()=>removeEntry(e.id)}>×</button></article>)}</div></>}</section>}</main>
  {selected&&<CardModal card={selected} close={()=>setSelected(null)} add={addCard}/>} {authOpen&&<AuthModal supabase={supabase} close={()=>setAuthOpen(false)} configured={configured}/>}<footer><span>CardFolio · Raw prices via TCGplayer</span><span>Pokémon trademarks belong to their respective owners. CardFolio is not affiliated with Pokémon.</span></footer></>;
}

function CardGrid({cards,loading,open}:{cards:Card[];loading:boolean;open:(c:Card)=>void}){return <div className="card-grid">{loading&&!cards.length?<div className="loading-grid">Loading live cards…</div>:cards.map(card=>{const p=prices(card);return <article className="card-tile" key={card.id}><button onClick={()=>open(card)}><div className="card-image"><img src={card.images.small} alt={card.name} loading="lazy"/><span className="badge">{card.rarity||"POKÉMON"}</span></div><div className="card-info"><h3>{card.name}</h3><div className="card-meta"><span>{card.set.name}</span><span className="card-price">{p.length?`${p.length>1?"From ":""}${usd(p[0].market)}`:"Unavailable"}</span></div></div></button></article>})}</div>}
function CardModal({card,close,add}:{card:Card;close:()=>void;add:(c:Card,v:string,p:number,q:number)=>void}){const p=prices(card),[variant,setVariant]=useState(p[0]?.variant||"unpriced"),[paid,setPaid]=useState((p[0]?.market||0)/100),[qty,setQty]=useState(1);return <div className="modal-shell" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-card"><button className="dialog-close" onClick={close}>×</button><div className="detail"><div className="detail-art"><img src={card.images.large} alt={card.name}/></div><div className="detail-body"><span className="kicker">{card.rarity}</span><h2>{card.name}</h2><div className="detail-sub">{card.set.name} · #{card.number}</div><div className="price-variants"><small className="price-heading">CURRENT RAW PRICES (USD)</small>{p.length?p.map(x=><div className="variant-price" key={x.variant}><span>{x.label}</span><strong>{usd(x.market)}</strong><small>Market{x.low?` · Low ${usd(x.low)}`:""}{x.mid?` · Mid ${usd(x.mid)}`:""}</small></div>):<div className="variant-price"><span>No verified price</span></div>}</div><div className="purchase raw-purchase"><label>Card variant<select value={variant} onChange={e=>{setVariant(e.target.value);setPaid((p.find(x=>x.variant===e.target.value)?.market||0)/100)}}>{p.length?p.map(x=><option key={x.variant} value={x.variant}>{x.label} · {usd(x.market)}</option>):<option value="unpriced">Unpriced raw card</option>}</select></label><label>Price paid<input type="number" min="0" step=".01" value={paid} onChange={e=>setPaid(Number(e.target.value))}/></label><label>Quantity<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><button className="add-btn" onClick={()=>add(card,variant,paid,qty)}>Add to portfolio</button></div></div></div></div></div>}
function AuthModal({supabase,close,configured}:{supabase:ReturnType<typeof createClient>|null;close:()=>void;configured:boolean}){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");async function act(mode:"in"|"up"){if(!supabase)return setError("Add Supabase credentials to .env.local first.");const result=mode==="in"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/auth/callback`}});if(result.error)setError(result.error.message);else close()}return <div className="modal-shell"><div className="modal-card auth-panel"><button className="dialog-close" onClick={close}>×</button><h2>Welcome to CardFolio</h2><p>Sign in to securely sync your raw-card collection.</p>{!configured&&<div className="notice">Supabase environment variables are not configured.</div>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<div className="auth-actions"><button onClick={()=>act("in")}>Sign in</button><button onClick={()=>act("up")}>Create account</button></div></div></div>}
